### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by brj** [jonknapp/fish.custom#1]
Hi @jonknapp          
I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to [fisherman](https://github.com/fisherman/fisherman):

* Why? fisherman/fisherman#69 (comment)

Everything, including legacy plugins/themes work great with fisherman, but new content is _no_ longer compatible with oh-my-fish.

**Comment by jonknapp** [comment]
Thanks for the helpful notification. I haven't used the Fish shell for quite a bit at this point and this project has just sat stagnant. I'll probably just remove it instead of upgrade.

I will be sure to check out fisherman if I come back to fish though, it sounds like a nice improvement.

**Comment by brj** [comment]
Thanks :)
